version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - test.a
      - test.b
      - test.c
    networks:
      - default

  test.a:
    image: php:7.4.13-apache
    container_name: test.a
    volumes:
      - ./src/test.a/:/var/www/html
    networks:
      - default

  test.b:
    image: php:7.4.13-apache
    container_name: test.b
    volumes:
      - ./src/test.b/:/var/www/html
    networks:
      - default

  test.c:
    image: php:7.4.13-apache
    container_name: test.c
    volumes:
      - ./src/test.c/:/var/www/html
    networks:
      - default

